Prepare for openjade-1.3.1-pre4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1365,10 +1365,10 @@ if test "$CXXFLAGS" = ""; then
 fi
 
 echo 'saving distribution makefiles...'
-test ! -f Makefile.dist && cp Makefile Makefile.dist
-test ! -f Makefile.lib.dist && cp Makefile.lib Makefile.lib.dist
-test ! -f Makefile.prog.dist && cp Makefile.prog Makefile.prog.dist
-test ! -f Makefile.comm.dist && cp Makefile.comm Makefile.comm.dist
+test ! -f Makefile.dist && test -f Makefile && cp Makefile Makefile.dist
+test ! -f Makefile.lib.dist && test -f Makefile.lib && cp Makefile.lib Makefile.lib.dist
+test ! -f Makefile.prog.dist && test -f Makefile.prog && cp Makefile.prog Makefile.prog.dist
+test ! -f Makefile.comm.dist && test -f Makefile.comm && cp Makefile.comm Makefile.comm.dist
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -4827,6 +4827,71 @@ else
   LIB_THREADS=""
 fi
 
+	echo "$as_me:$LINENO: checking whether size_t is unsigned int" >&5
+echo $ECHO_N "checking whether size_t is unsigned int... $ECHO_C" >&6
+	ac_cv_size_t_is_uint=no
+
+	ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <unistd.h>
+
+                       template<class T> class foo { };
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+			foo<size_t> x;
+			foo<unsigned int> y;
+			x = y;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_size_t_is_uint=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+	ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	echo "$as_me:$LINENO: result: $ac_cv_size_t_is_uint" >&5
+echo "${ECHO_T}$ac_cv_size_t_is_uint" >&6
+	test "$ac_cv_size_t_is_uint" = "yes" && cat >>confdefs.h <<\_ACEOF
+#define SIZE_T_IS_UINT 1
+_ACEOF
+
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4838,8 +4903,7 @@ echo $ECHO_N "checking support for bool... $ECHO_C" >&6
 if test "${ac_cv_typedef_bool+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-
-cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
@@ -6452,7 +6516,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6455 "configure"' > conftest.$ac_ext
+  echo '#line 6519 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6974,7 +7038,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:6977: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:7041: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -8589,7 +8653,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8592 "configure"
+#line 8656 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8686,7 +8750,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8689 "configure"
+#line 8753 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
